name: Build and Deploy IG

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out repo
      - name: Checkout source
        uses: actions/checkout@v4

      # 1a. Debug info to check if running from a fork
      #- name: Check if running from a fork
      #  run: |
      #    echo "Repository: $GITHUB_REPOSITORY"
      #    echo "Event repository: $(jq -r .pull_request.head.repo.full_name < $GITHUB_EVENT_PATH || echo $GITHUB_REPOSITORY)"


      # 2. Set up Node.js (your version)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      # 3. Install Sushi globally
      - name: Install Sushi
        run: npm install -g fsh-sushi

      # 4. Install IG dependencies (e.g., AU Core) from package.json
      - name: Install IG dependencies
        run: npm ci

      # 5. Cache publisher.jar
      - name: Cache IG Publisher
        id: cache-publisher
        uses: actions/cache@v4
        with:
          path: ./publisher.jar
          key: publisher-1.0.0  # bump this if you want to force re-download

      # 6. Download publisher.jar if not cached
      - name: Download IG Publisher
        if: steps.cache-publisher.outputs.cache-hit != 'true'
        run: |
          curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o publisher.jar

      # 7. Run Sushi
      - name: Run Sushi
        run: sushi .

      # Install Ruby and Jekyll for IG rendering
      - name: Install Ruby and Jekyll
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential zlib1g-dev
          sudo gem install jekyll bundler

      # 8. Run IG Publisher
      - name: Run IG Publisher
        run: java -jar publisher.jar -ig ig.ini

      # 9. Deploy to gh-pages branch
      - name: Deploy IG to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
          force_orphan: true
  
